'use client'; import { useState, useEffect, useCallback } from 'react';
import { ChatProvider, useChatWebSocket } from '@imajin/chat';
import { apiFetch } from '@imajin/config';
import { EventChat } from './components/EventChat'; const CHAT_URL = process.env.NEXT_PUBLIC_CHAT_URL || 'http://localhost:3007';
// Use same-origin proxy for access checks (cross-origin cookie forwarding is unreliable)
const AUTH_URL = ''; // empty = same origin, proxied via /api/access/[did]
const MEDIA_URL = process.env.NEXT_PUBLIC_MEDIA_URL || 'http://localhost:3009'; interface AccordionContentProps { eventId: string; eventDid: string; isExpanded: boolean; onUnreadChange: React.Dispatch<React.SetStateAction<number>>;
} function AccordionContent({ eventId, eventDid, isExpanded, onUnreadChange }: AccordionContentProps) { const { lastMessage } = useChatWebSocket(eventDid); // Increment unread count when a new message arrives while collapsed useEffect(() => { if (!lastMessage || isExpanded) return; if (lastMessage.type === 'new_message') { onUnreadChange(prev => prev + 1); } }, [lastMessage, isExpanded, onUnreadChange]); // Reset unread when expanded useEffect(() => { if (isExpanded) onUnreadChange(0); }, [isExpanded, onUnreadChange]); if (!isExpanded) return null; return ( <div className="border-t border-white/10 border-white/10 px-6 py-4"> <EventChat did={eventDid} eventId={eventId} compact /> </div> );
} interface EventLobbyAccordionProps { eventId: string; eventDid: string;
} export function EventLobbyAccordion({ eventId, eventDid }: EventLobbyAccordionProps) { const [hasAccess, setHasAccess] = useState<boolean | null>(null); const [isExpanded, setIsExpanded] = useState(false); const [unreadCount, setUnreadCount] = useState(0); // Check event access on mount (ticket holder OR organizer) useEffect(() => { async function checkAccess() { try { const res = await apiFetch(`/api/events/${eventId}/my-ticket`); if (res.ok) { const data = await res.json(); setHasAccess(data.hasAccess || data.hasTicket || false); } else { setHasAccess(false); } } catch { setHasAccess(false); } } checkAccess(); }, [eventId]); const handleUnreadChange = useCallback<React.Dispatch<React.SetStateAction<number>>>( (action) => setUnreadCount(action), [] ); // Render nothing if no access or not authenticated if (hasAccess === false || hasAccess === null) { return null; } return ( <ChatProvider chatUrl={CHAT_URL} authUrl={AUTH_URL} mediaUrl={MEDIA_URL}> <div className="bg-surface-surface bg-surface-elevated/50 backdrop-blur-sm overflow-hidden"> {/* Collapsed Header */} <button onClick={() => setIsExpanded(!isExpanded)} className="w-full px-6 py-4 flex items-center justify-between hover:bg-surface-elevated dark:hover:bg-surface-elevated/80 transition" > <div className="flex items-center gap-3"> <span className="text-2xl">💬</span> <span className="font-mono font-semibold text-lg">Event Chat</span> </div> <div className="flex items-center gap-3"> {!isExpanded && unreadCount > 0 && ( <span className="px-3 py-1 bg-imajin-orange text-primary text-xs font-semibold rounded-full"> {unreadCount} </span> )} <span className={`text-secondary transition-transform ${isExpanded ? 'rotate-180' : ''}`}> ▼ </span> </div> </button> <AccordionContent eventId={eventId} eventDid={eventDid} isExpanded={isExpanded} onUnreadChange={handleUnreadChange} /> </div> </ChatProvider> );
}
