/**
 * GET + PUT + DELETE /warp/api/environment (#1632)
 *
 * The session owner's default Warp cloud environment — the persistent workspace
 * (pre-cloned repo, deps installed) that dispatches land in when they name none.
 *
 * GET    — `{ environmentId: string | null }`.
 * PUT    — body `{ environmentId }`; replaces the stored default.
 * DELETE — clears it, so dispatch falls back to the node default, then to Warp's.
 *
 * ## Why this is not on /warp/api/seal
 * The seal route is generated by the static-secret factory and is about custody
 * of the Agent key: POST seals, DELETE revokes the delegation grant and kills
 * dispatch. An environment UID is a non-secret preference with none of those
 * semantics, and folding it in would make `DELETE /warp/api/seal` ambiguous
 * between "revoke my credential" and "forget my environment".
 *
 * ## Setting the node-wide default
 * There is no separate admin route: this acts on the *acting* DID, so a session
 * acting as the node DID sets the node's default through this same endpoint. That
 * is the whole node-wide configuration mechanism — deliberately not an env var,
 * so it is per-DID, visible in the connector card, and auditable like any other
 * vault field.
 */
import { NextResponse, type NextRequest } from 'next/server';
import { requireAuth, resolveActingDid } from '@imajin/auth';
import { createLogger } from '@imajin/logger';
import { corsHeaders, corsOptions } from '@/src/lib/kernel/cors';
import {
  clearEnvironmentId,
  isValidEnvironmentId,
  readEnvironmentId,
  writeEnvironmentId,
} from '@/src/lib/warp/environment';

const log = createLogger('kernel');

export async function OPTIONS(request: NextRequest) {
  return corsOptions(request);
}

/**
 * Resolve the acting DID, or the error response to return instead.
 *
 * All three verbs need the identical preamble, and returning the response rather
 * than throwing keeps each handler's happy path flat.
 */
async function actingDid(
  request: NextRequest,
  cors: Record<string, string>,
): Promise<{ did: string } | { response: NextResponse }> {
  const auth = await requireAuth(request);
  if ('error' in auth) {
    return {
      response: NextResponse.json({ error: auth.error }, { status: auth.status, headers: cors }),
    };
  }
  return { did: resolveActingDid(auth.identity) };
}

export async function GET(request: NextRequest) {
  const cors = corsHeaders(request);

  const resolved = await actingDid(request, cors);
  if ('response' in resolved) return resolved.response;

  const environmentId = await readEnvironmentId(resolved.did);
  return NextResponse.json({ environmentId: environmentId ?? null }, { headers: cors });
}

export async function PUT(request: NextRequest) {
  const cors = corsHeaders(request);

  const resolved = await actingDid(request, cors);
  if ('response' in resolved) return resolved.response;

  let body: { environmentId?: unknown };
  try {
    body = (await request.json()) as { environmentId?: unknown };
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400, headers: cors });
  }

  const environmentId =
    typeof body.environmentId === 'string' ? body.environmentId.trim() : '';

  // Validated here as well as in writeEnvironmentId so a bad value is a 400 with
  // the rule stated, not a 500 from a rejected promise.
  if (!isValidEnvironmentId(environmentId)) {
    return NextResponse.json(
      {
        error:
          'environmentId must be a non-empty token of letters, digits, hyphens, or underscores',
      },
      { status: 400, headers: cors },
    );
  }

  try {
    await writeEnvironmentId(resolved.did, environmentId);
  } catch (err) {
    log.error(
      { err: String(err), principalDid: resolved.did },
      'Warp environment default write failed',
    );
    return NextResponse.json(
      { error: 'Failed to store the Warp environment default', detail: String(err) },
      { status: 500, headers: cors },
    );
  }

  return NextResponse.json({ environmentId }, { headers: cors });
}

export async function DELETE(request: NextRequest) {
  const cors = corsHeaders(request);

  const resolved = await actingDid(request, cors);
  if ('response' in resolved) return resolved.response;

  let cleared: boolean;
  try {
    cleared = await clearEnvironmentId(resolved.did);
  } catch (err) {
    log.error(
      { err: String(err), principalDid: resolved.did },
      'Warp environment default clear failed',
    );
    return NextResponse.json(
      { error: 'Failed to clear the Warp environment default', detail: String(err) },
      { status: 500, headers: cors },
    );
  }

  return NextResponse.json({ cleared, environmentId: null }, { headers: cors });
}
