import { redirect } from 'next/navigation';
import { getSession } from '@imajin/auth';
import { db, events, ticketTypes } from '@/src/db';
import { eq, desc } from 'drizzle-orm';
import Link from 'next/link';
import { PayoutSetupBanner } from '@imajin/ui'; const PAY_URL = process.env.NEXT_PUBLIC_PAY_URL || 'https://pay.imajin.ai';
import { EventCard } from './event-card'; interface EventWithStats { id: string; title: string; startsAt: Date; imageUrl: string | null; status: string; statusBadge: string; ticketsSold: number; revenue: number;
} export default async function DashboardPage() { const session = await getSession(); if (!session) { const authUrl = process.env.NEXT_PUBLIC_AUTH_URL || 'https://auth.imajin.ai'; const eventsUrl = process.env.NEXT_PUBLIC_EVENTS_URL || 'https://events.imajin.ai'; redirect(`${authUrl}/login?next=${encodeURIComponent(`${eventsUrl}/dashboard`)}`); } const did = session.actingAs || session.id; const userEvents = await db.select().from(events).where(eq(events.creatorDid, did)).orderBy(desc(events.createdAt)); const eventsWithStats = await Promise.all(userEvents.map(async (event) => { const types = await db.select().from(ticketTypes).where(eq(ticketTypes.eventId, event.id)); const totalTicketsSold = types.reduce((sum, t) => sum + (t.sold || 0), 0); const totalRevenue = types.reduce((sum, t) => sum + (t.sold || 0) * t.price, 0); let statusBadge = event.status; const now = new Date(); if (event.status === 'published') { statusBadge = new Date(event.startsAt) < now ? 'past' : 'live'; } return { ...event, ticketsSold: totalTicketsSold, revenue: totalRevenue, statusBadge, ticketTypes: types }; })); return ( <div className="max-w-7xl mx-auto"> <PayoutSetupBanner did={did} payUrl={PAY_URL} message="Connect your bank account to receive ticket revenue" /> {/* Header */} <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"> <div> <h1 className="text-3xl md:text-4xl font-mono font-bold mb-2">My Events</h1> <p className="text-secondary text-secondary"> Manage your events and track ticket sales </p> </div> <Link href="/create" className="inline-flex items-center justify-center px-6 py-3 bg-imajin-orange hover:bg-imajin-orange text-primary font-semibold transition-colors" > <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /> </svg> Create Event </Link> </div> {/* Events Grid or Empty State */} {eventsWithStats.length === 0 ? ( <div className="bg-surface-surface bg-surface-elevated/50 backdrop-blur-sm p-12 text-center"> <div className="max-w-md mx-auto"> <div className="text-6xl mb-4">🎉</div> <h2 className="text-2xl font-mono font-bold mb-3">Create your first event</h2> <p className="text-muted text-secondary mb-6"> Start bringing people together. Create an event, sell tickets, and build your community. </p> <Link href="/create" className="inline-flex items-center justify-center px-8 py-3 bg-imajin-orange hover:bg-imajin-orange text-primary font-semibold transition-colors" > <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /> </svg> Create Event </Link> </div> </div> ) : ( <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"> {eventsWithStats.map((event) => ( <EventCard key={event.id} event={event} /> ))} </div> )} </div> );
}
