'use client'; import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { apiFetch } from '@imajin/config'; type EventStatus = 'draft' | 'published' | 'paused' | 'cancelled' | 'completed'; const STATUS_TRANSITIONS: Record<EventStatus, EventStatus[]> = { draft: ['published'], published: ['paused', 'cancelled', 'completed'], paused: ['published', 'cancelled'], cancelled: [], completed: [],
}; const STATUS_BADGE_STYLES: Record<EventStatus, string> = { draft: 'bg-surface-elevated text-primary border border-white/10', published: 'bg-success/10 text-success border border-green-700', paused: 'bg-warning/10 text-warning border border-yellow-700', cancelled: 'bg-error/10 text-error border border-red-700', completed: 'bg-info/10 text-info border border-info/30',
}; const TRANSITION_LABELS: Partial<Record<string, string>> = { 'draft->published': 'Publish', 'published->paused': 'Pause', 'published->cancelled': 'Cancel Event', 'published->completed': 'Mark Complete', 'paused->published': 'Resume', 'paused->cancelled': 'Cancel Event',
}; const TRANSITION_STYLES: Partial<Record<string, string>> = { 'draft->published': 'bg-green-600 hover:bg-green-700 text-primary', 'published->paused': 'bg-yellow-600 hover:bg-yellow-700 text-primary', 'published->cancelled': 'bg-red-600 hover:bg-red-700 text-primary', 'published->completed': 'bg-blue-600 hover:bg-blue-700 text-primary', 'paused->published': 'bg-green-600 hover:bg-green-700 text-primary', 'paused->cancelled': 'bg-red-600 hover:bg-red-700 text-primary',
}; interface Props { eventId: string; currentStatus: string;
} export function EventStatusControls({ eventId, currentStatus }: Props) { const router = useRouter(); const [status, setStatus] = useState<EventStatus>((currentStatus || 'draft') as EventStatus); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const nextStatuses = STATUS_TRANSITIONS[status] || []; const handleTransition = async (newStatus: EventStatus) => { if (newStatus === 'cancelled' || newStatus === 'completed') { const messages: Record<string, string> = { cancelled: 'Are you sure you want to cancel this event? This cannot be undone.', completed: 'Are you sure you want to mark this event as completed? This cannot be undone.', }; const confirmed = window.confirm(messages[newStatus] || 'Are you sure?'); if (!confirmed) return; } setLoading(true); setError(null); try { const res = await apiFetch(`/api/events/${eventId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: newStatus }), }); if (!res.ok) { const data = await res.json(); throw new Error(data.error || 'Failed to update status'); } setStatus(newStatus); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'Something went wrong'); } finally { setLoading(false); } }; return ( <div className="bg-surface-surface bg-surface-elevated p-4 mb-6"> <div className="flex items-center justify-between flex-wrap gap-4"> <div className="flex items-center gap-3"> <span className="text-sm text-secondary text-secondary">Event Status</span> <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium capitalize ${STATUS_BADGE_STYLES[status]}`}> {status} </span> </div> {nextStatuses.length > 0 && ( <div className="flex items-center gap-2 flex-wrap"> {nextStatuses.map((next) => { const key = `${status}->${next}`; return ( <button key={next} onClick={() => handleTransition(next)} disabled={loading} className={`px-4 py-2 text-sm font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed ${TRANSITION_STYLES[key] || 'bg-surface-elevated hover:bg-surface-elevated text-primary'}`} > {loading ? '...' : (TRANSITION_LABELS[key] || next)} </button> ); })} </div> )} </div> {error && ( <p className="mt-2 text-sm text-error">{error}</p> )} </div> );
}
